name: Docker CI\CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t shahmeer312/DevOps_Q1_A4 .

    - name: Log in to DockerHub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push to DockerHub
      run: docker push shahmeer312/DevOps_Q1_A4
